export const calendar = {
  id: "1234",
  type: "calendar",
  name: "Some Calendar",
  description: "Calendar description",
  color: "#2ecc87",
  order: 0,
  imageUrl: "https://attachments.timetreeapp.com/path/to/image.png",
  createdAt: "2019-04-01T12:34:56.000Z",
  labels: [
    {
      id: "1234,1",
      type: "label",
      name: "label title(empty if default)",
      color: "#2ecc87",
    },
    { id: "1234,2", type: "label" },
    { id: "1234,3", type: "label" },
    { id: "1234,4", type: "label" },
    { id: "1234,5", type: "label" },
    { id: "1234,6", type: "label" },
    { id: "1234,7", type: "label" },
    { id: "1234,8", type: "label" },
    { id: "1234,9", type: "label" },
    { id: "1234,10", type: "label" },
  ],
  members: [
    {
      id: "1234,12345",
      type: "user",
      name: "User1",
      description: "blah blah blah",
      imageUrl: "https://attachments.timetreeapp.com/path/to/image.png",
    },
    { id: "1234,23456", type: "user" },
  ],
};
